apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    app: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: piomin/employee:1.1
        ports:
          - containerPort: 8080
        env:   # Setting Enviornmental Variables
          - name: MONGO_DATABASE  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: employee 
                key: database
          - name: MONGO_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: employee # Secret Name
                key: username
          - name: MONGO_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: employee
                key: password     
        
---
apiVersion: v1
kind: Service
metadata:
  name: employee
  labels:
    app: employee
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: employee
  type: NodePort