kind: ConfigMap
apiVersion: v1
metadata:
  name: organization
data:
  logging.pattern.console: "%d{HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  spring.cloud.kubernetes.discovery.all-namespaces: "true"
  database: "admin"
  host: "mongodb.default"