branch-service-mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=secret123
    - MYSQL_DATABASE=demo
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=secret

spring-bank-branch-service-kubernetes:
  image: rkp/spring-bank-branch-service-kubernetes
  links:
    - branch-service-mysql:mysql
  ports:
    - 8080:8080
  expose:
    - 8080
  environment:
    - "SPRING_PROFILES_ACTIVE=docker"
