

security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?allowPublicKeyRetrieval=true&useSSL=FALSE
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 9000

  ssl.key-store-password: changeit
  ssl.key-store: ssl/resources/oaauth-ssl-key.p12
  ssl.key-store-type: PKCS12